name: PMP
version: 1.0.0
slug: pmp
description: Панель мониторинга питанием для трех PZEM-016 220В 100А.
icon: /local/icon.png
startup: application
boot: auto
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
ports:
  5000/tcp: 5000
options:
  flask_port: 5000
schema:
  flask_port: int
